import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";

/**
 * Storage backend for uploaded files. The MVP ships a local-disk
 * implementation; an S3-compatible backend can implement the same interface.
 */
export interface FileStorage {
  put(userId: string, data: Buffer): Promise<string>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

export class LocalFileStorage implements FileStorage {
  constructor(private readonly root: string) {}

  private resolve(key: string): string {
    // Keys are generated by us ("<uuid>/<uuid>") but are validated anyway.
    if (!/^[0-9a-f-]{36}\/[0-9a-f-]{36}$/.test(key)) throw new Error("Clé de stockage invalide.");
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error("Chemin de stockage invalide.");
    return full;
  }

  async put(userId: string, data: Buffer): Promise<string> {
    if (!/^[0-9a-f-]{36}$/.test(userId)) throw new Error("Identifiant utilisateur invalide.");
    const key = `${userId}/${randomUUID()}`;
    const full = this.resolve(key);
    await fs.mkdir(path.dirname(full), { recursive: true, mode: 0o700 });
    await fs.writeFile(full, data, { mode: 0o600 });
    return key;
  }

  async get(key: string): Promise<Buffer> {
    return fs.readFile(this.resolve(key));
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.resolve(key), { force: true });
  }
}

let storage: FileStorage | undefined;
export function getStorage(): FileStorage {
  if (!storage) storage = new LocalFileStorage(process.env.ATLAS_STORAGE_DIR || "./storage");
  return storage;
}
export function setStorageForTests(s: FileStorage) {
  storage = s;
}
