import { constants, promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";

/**
 * Storage backend for uploaded files. The MVP ships a local-disk
 * implementation; an S3-compatible backend can implement the same interface.
 */
export interface FileStorage {
  put(userId: string, data: Buffer): Promise<string>;
  /** Throws MissingFileError when the file is not in storage. */
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

/** The stored file referenced by a document is gone (lost volume, manual deletion…). */
export class MissingFileError extends Error {
  constructor(public readonly key: string) {
    super("Fichier absent du stockage.");
  }
}

export class StorageConfigError extends Error {}

const UUID = /^[0-9a-f-]{36}$/;

/**
 * Storage directory, as an absolute path. In production it must be set
 * explicitly to an absolute path (a persistent volume): a relative default
 * would depend on the working directory and silently land on an ephemeral disk.
 */
export function resolveStorageDir(env: NodeJS.ProcessEnv = process.env): string {
  const dir = env.ATLAS_STORAGE_DIR?.trim();
  if (env.NODE_ENV === "production") {
    if (!dir) {
      throw new StorageConfigError(
        "ATLAS_STORAGE_DIR doit être défini en production (chemin absolu d'un volume persistant).",
      );
    }
    if (!path.isAbsolute(dir)) {
      throw new StorageConfigError(`ATLAS_STORAGE_DIR doit être un chemin absolu en production (reçu : « ${dir} »).`);
    }
  }
  return path.resolve(/*turbopackIgnore: true*/ dir || "./storage");
}

/**
 * Storage directory for maintenance scripts (purge, storage:check), whatever
 * NODE_ENV is: an absolute path is always required, so a script launched with
 * an incomplete environment can never clean up another directory.
 */
export function resolveMaintenanceStorageDir(env: NodeJS.ProcessEnv = process.env): string {
  const dir = env.ATLAS_STORAGE_DIR?.trim();
  if (!dir || !path.isAbsolute(dir)) {
    throw new StorageConfigError(
      `Les scripts de maintenance exigent ATLAS_STORAGE_DIR en chemin absolu, identique à celui de l'application (reçu : « ${dir ?? ""} »).`,
    );
  }
  return path.resolve(/*turbopackIgnore: true*/ dir);
}

/** Creates the directory if needed and checks that the server can write to it. */
export async function checkStorageDir(dir: string) {
  try {
    await fs.mkdir(dir, { recursive: true, mode: 0o700 });
    await fs.access(dir, constants.R_OK | constants.W_OK);
  } catch (e) {
    throw new StorageConfigError(`Répertoire de stockage inutilisable (${dir}) : ${(e as Error).message}`);
  }
}

export type StoredFile = { key: string; size: number; modifiedAt: Date };

export class LocalFileStorage implements FileStorage {
  readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(/*turbopackIgnore: true*/ root);
  }

  private resolve(key: string): string {
    // Keys are generated by us ("<uuid>/<uuid>") but are validated anyway.
    if (!/^[0-9a-f-]{36}\/[0-9a-f-]{36}$/.test(key)) throw new Error("Clé de stockage invalide.");
    const full = path.resolve(this.root, key);
    if (!full.startsWith(this.root + path.sep)) throw new Error("Chemin de stockage invalide.");
    return full;
  }

  async put(userId: string, data: Buffer): Promise<string> {
    if (!UUID.test(userId)) throw new Error("Identifiant utilisateur invalide.");
    const key = `${userId}/${randomUUID()}`;
    const full = this.resolve(key);
    await fs.mkdir(path.dirname(full), { recursive: true, mode: 0o700 });
    await fs.writeFile(full, data, { mode: 0o600 });
    return key;
  }

  async get(key: string): Promise<Buffer> {
    try {
      return await fs.readFile(this.resolve(key));
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") throw new MissingFileError(key);
      throw e;
    }
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.resolve(key), { force: true });
  }

  /** Every stored file (entries that do not look like our keys are ignored). */
  async list(): Promise<StoredFile[]> {
    const out: StoredFile[] = [];
    for (const dir of await this.userDirs()) {
      for (const name of await fs.readdir(path.join(this.root, dir))) {
        if (!UUID.test(name)) continue;
        const st = await fs.stat(path.join(this.root, dir, name));
        if (st.isFile()) out.push({ key: `${dir}/${name}`, size: st.size, modifiedAt: st.mtime });
      }
    }
    return out;
  }

  /** Per-user directories left empty (e.g. after an account deletion). */
  async emptyUserDirs(): Promise<string[]> {
    const out: string[] = [];
    for (const dir of await this.userDirs()) {
      if ((await fs.readdir(path.join(this.root, dir))).length === 0) out.push(dir);
    }
    return out;
  }

  async removeEmptyUserDir(dir: string): Promise<void> {
    if (!UUID.test(dir)) throw new Error("Répertoire de stockage invalide.");
    await fs.rmdir(path.join(this.root, dir));
  }

  private async userDirs(): Promise<string[]> {
    let entries;
    try {
      entries = await fs.readdir(this.root, { withFileTypes: true });
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return [];
      throw e;
    }
    return entries.filter((e) => e.isDirectory() && UUID.test(e.name)).map((e) => e.name);
  }
}

let storage: FileStorage | undefined;
export function getStorage(): FileStorage {
  if (!storage) storage = new LocalFileStorage(resolveStorageDir());
  return storage;
}
export function setStorageForTests(s: FileStorage) {
  storage = s;
}
